# $ dart run build_runner build

targets:
  $default:
    sources:
      include:
        - "lib/**"
        - "pubspec.yaml"
        - "$package$"
      exclude:
        - test/**
    builders:
      source_gen|combining_builder:
        generate_for:
          - lib/model/*.dart
        options:
          build_extensions:
            "^lib/model/{{}}.dart": "lib/model/generate/{{}}.g.dart"

      json_serializable:
        generate_for:
          - lib/model/*.dart
        options:
          explicit_to_json: true
          include_if_null: false

      freezed:
        generate_for:
          - lib/model/*.dart
        options:
          build_extensions:
            "^lib/model/{{}}.dart": "lib/model/generate/{{}}.freezed.dart"
