name: pop_qr
description: "Pop QR lets users store links, and present them as QR codes for face-to-face sharing."

# publish_to: 'none' -> これにより、パッケージが pub.dev に誤って公開されるのを防ぎます。
publish_to: "none"

version: 1.0.0+1

environment:
  # Dart SDK のバージョン制約
  sdk: ^3.7.2

dependencies:
  # Flutter SDK自体
  flutter:
    sdk: flutter

  # iOS スタイルのアイコンを使用するためのパッケージ
  cupertino_icons: ^1.0.8

  # 状態管理パッケージ
  flutter_riverpod: ^2.5.1
  hooks_riverpod: ^2.5.1
  flutter_hooks: ^0.21.0

  # QRコード生成パッケージ
  qr_flutter: ^4.1.0

  # データ永続化パッケージ
  shared_preferences: ^2.2.2

  # コード生成
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

  # ユーティリティ
  uuid: ^4.3.3
  url_launcher: ^6.3.1

# 開発中にのみ必要なパッケージ
dev_dependencies:
  flutter_test:
    sdk: flutter

  # 推奨されるリントルールセット
  flutter_lints: ^5.0.0

  # コード生成ツール
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1

  # モックパッケージ
  mockito: ^5.4.4

# $ flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: true # Android 用アイコンを生成
  ios: true # iOS 用アイコンを生成
  image_path: "assets/app_icon/app_icon_balloon_qr.png" # 元となるアイコン画像
  # image_path: "assets/app_icon/app_icon_focus_qr.png"
  # image_path: "assets/app_icon/app_icon_focus_link.png"
  # image_path: "assets/app_icon/app_icon_balloon_link.png"

flutter:
  uses-material-design: true

  assets:
    - assets/app_icon/app_icon_balloon_link.png
    - assets/app_icon/app_icon_balloon_qr.png
    - assets/app_icon/app_icon_focus_link.png
    - assets/app_icon/app_icon_focus_qr.png
    - lib/resource/emoji_list.txt
