name: Build for Production

on:
  workflow_call:
    inputs:
      release_tag:
        description: "GitHubリリースのためのオプションのリリース Tag (例: v1.2.3)"
        required: false
        type: string
      pr_number:
        description: "Pull Request Number (if applicable, otherwise 0)"
        required: false
        type: number
        default: 0

jobs:
  build-android-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2.12.0
        with:
          flutter-version: '3.29.3'
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Run build_runner
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Build Android App Bundle (Release, Unsigned/Debug Key)
        run: flutter build appbundle --release

      - name: Build Android APKs (Release, Unsigned/Debug Key)
        run: flutter build apk --release --split-per-abi

      - name: Upload Android App Bundle Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ci-android-bundle
          path: build/app/outputs/bundle/release/*.aab
          retention-days: 7

      - name: Upload Android APKs Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ci-android-apks
          path: build/app/outputs/flutter-apk/*-release.apk
          retention-days: 7

  create-github-release:
    needs: [build-android-release] # build-ios-release を削除
    runs-on: ubuntu-latest
    if: ${{ inputs.release_tag != '' && success() }}
    permissions:
      contents: write
      actions: read
    steps:
      - name: Download Android Bundle Artifact
        uses: actions/download-artifact@v4
        with:
          name: ci-android-bundle
          path: ./build/app/outputs/bundle/release

      - name: Download Android APKs Artifact
        uses: actions/download-artifact@v4
        with:
          name: ci-android-apks
          path: ./build/app/outputs/flutter-apk

      - name: Create GitHub Release Draft
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ inputs.release_tag }}
          name: Release ${{ inputs.release_tag }}
          draft: true
          prerelease: false
          files: |
            ./build/app/outputs/bundle/release/*.aab
            ./build/app/outputs/flutter-apk/*-release.apk
            # ./build/ios/ipa/*.ipa # この行をコメントアウトまたは削除
          token: ${{ secrets.GITHUB_TOKEN }}